### ISSUE TITLE
BUG#1 - A biblioteca do Mapa está dando conflito com o Next [RESOLVIDO]

### ISSUE THREAD

**Issue by care4you** [Care-4-you/AgendaSaude.web#34]

**Comment by care4you** [comment]
Ao tentar fazer o build da aplicação na vercel ocorria o seguinte erro:

```
ReferenceError: window is not defined
    at D:\Projetos\AgendaSaude.web\.next\server\app\map\page.js:1:5871
    at 4673 (D:\Projetos\AgendaSaude.web\.next\server\app\map\page.js:1:152328)
    at t (D:\Projetos\AgendaSaude.web\.next\server\webpack-runtime.js:1:128)
    at 8940 (D:\Projetos\AgendaSaude.web\.next\server\app\map\page.js:1:152684)
    at t (D:\Projetos\AgendaSaude.web\.next\server\webpack-runtime.js:1:128)
    at F (D:\Projetos\AgendaSaude.web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:94693)
    at j (D:\Projetos\AgendaSaude.web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:93244)
    at rP (D:\Projetos\AgendaSaude.web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:33905)
    at nL (D:\Projetos\AgendaSaude.web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:62423)
    at nB (D:\Projetos\AgendaSaude.web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:67657)

Error occurred prerendering page "/map".

```
Esse erro ocorria por causa da biblioteca 'react-leaflet', que deveria rodar somente no browser, ser executada ainda no ambiente node do next. A solução foi fazer uso de um dynamic import do next:

![Image](https://github.com/orgs/Care-4-you/projects/7/assets/127883797/b7a875fe-064c-4fc3-82d7-994c5674f55f)

O dynamic import faz com que a biblioteca seja executada somente no ambiente do browser.
